import type {
  ComparingDifficulty,
  ComparingNumbersSheet,
  ComparingOperand,
  ComparingProblem
} from "./types";

function whole(value: number): ComparingOperand {
  return { kind: "whole", value };
}

function decimal(text: string): ComparingOperand {
  return { kind: "decimal", text };
}

function fraction(
  numerator: number,
  denominator: number,
  whole?: number
): ComparingOperand {
  return whole === undefined
    ? { kind: "fraction", numerator, denominator }
    : { kind: "fraction", whole, numerator, denominator };
}

function pair(
  difficulty: ComparingDifficulty,
  left: ComparingOperand,
  right: ComparingOperand
): ComparingProblem {
  return { difficulty, left, right };
}

export const sheets = [
  {
    page: 1,
    title: "Comparing Whole Numbers",
    label: "Comparing whole numbers A",
    kind: "whole",
    instruction:
      "Write <, > or = in each box. Start with two-digit numbers, then compare place value in larger numbers.",
    problems: [
      pair("easy", whole(23), whole(32)),
      pair("easy", whole(45), whole(45)),
      pair("easy", whole(18), whole(81)),
      pair("easy", whole(70), whole(69)),
      pair("easy", whole(9), whole(12)),
      pair("easy", whole(15), whole(51)),
      pair("easy", whole(27), whole(27)),
      pair("easy", whole(40), whole(39)),
      pair("easy", whole(64), whole(46)),
      pair("easy", whole(8), whole(11)),
      pair("easy", whole(90), whole(89)),
      pair("easy", whole(33), whole(36)),
      pair("easy", whole(25), whole(52)),
      pair("easy", whole(11), whole(11)),
      pair("easy", whole(48), whole(84)),
      pair("medium", whole(305), whole(350)),
      pair("medium", whole(199), whole(201)),
      pair("medium", whole(440), whole(404)),
      pair("medium", whole(712), whole(721)),
      pair("medium", whole(1000), whole(999)),
      pair("medium", whole(508), whole(580)),
      pair("medium", whole(250), whole(205)),
      pair("medium", whole(616), whole(661)),
      pair("medium", whole(820), whole(802)),
      pair("medium", whole(474), whole(447)),
      pair("medium", whole(909), whole(990)),
      pair("medium", whole(333), whole(323)),
      pair("hard", whole(4582), whole(4528)),
      pair("hard", whole(3090), whole(3900)),
      pair("hard", whole(10002), whole(9998)),
      pair("hard", whole(2020), whole(2200)),
      pair("hard", whole(8888), whole(8898)),
      pair("hard", whole(7007), whole(7070)),
      pair("hard", whole(4554), whole(4545)),
      pair("hard", whole(12000), whole(11999)),
      pair("hard", whole(6066), whole(6606)),
      pair("hard", whole(2112), whole(2211)),
      pair("hard", whole(8088), whole(8808)),
      pair("hard", whole(15015), whole(15150))
    ]
  },
  {
    page: 2,
    title: "Comparing Whole Numbers",
    label: "Comparing whole numbers B",
    kind: "whole",
    instruction:
      "Write <, > or = in each box. Watch zeros and swapped digits — they change the value of the number.",
    problems: [
      pair("easy", whole(56), whole(65)),
      pair("easy", whole(80), whole(80)),
      pair("easy", whole(34), whole(43)),
      pair("easy", whole(19), whole(91)),
      pair("easy", whole(100), whole(99)),
      pair("easy", whole(47), whole(74)),
      pair("easy", whole(22), whole(22)),
      pair("easy", whole(60), whole(59)),
      pair("easy", whole(13), whole(31)),
      pair("easy", whole(85), whole(58)),
      pair("easy", whole(7), whole(10)),
      pair("easy", whole(41), whole(14)),
      pair("easy", whole(28), whole(82)),
      pair("easy", whole(55), whole(55)),
      pair("easy", whole(16), whole(61)),
      pair("medium", whole(2450), whole(2405)),
      pair("medium", whole(6007), whole(6070)),
      pair("medium", whole(1111), whole(1011)),
      pair("medium", whole(5500), whole(5050)),
      pair("medium", whole(9099), whole(9909)),
      pair("medium", whole(3030), whole(3300)),
      pair("medium", whole(8080), whole(8008)),
      pair("medium", whole(4444), whole(4144)),
      pair("medium", whole(7070), whole(7700)),
      pair("medium", whole(1212), whole(1221)),
      pair("medium", whole(9090), whole(9009)),
      pair("medium", whole(3663), whole(3366)),
      pair("hard", whole(12345), whole(12435)),
      pair("hard", whole(20020), whole(20200)),
      pair("hard", whole(99909), whole(99099)),
      pair("hard", whole(50005), whole(50050)),
      pair("hard", whole(101010), whole(110010)),
      pair("hard", whole(80808), whole(80088)),
      pair("hard", whole(45054), whole(45504)),
      pair("hard", whole(30003), whole(30030)),
      pair("hard", whole(99999), whole(100001)),
      pair("hard", whole(11011), whole(11101)),
      pair("hard", whole(40404), whole(44004)),
      pair("hard", whole(25052), whole(25502))
    ]
  },
  {
    page: 3,
    title: "Comparing Decimals",
    label: "Comparing decimals A",
    kind: "decimal",
    instruction:
      "Write <, > or = in each box. Line up the decimal points and compare digit by digit from the left.",
    problems: [
      pair("easy", decimal("0.3"), decimal("0.5")),
      pair("easy", decimal("0.7"), decimal("0.70")),
      pair("easy", decimal("1.2"), decimal("1.5")),
      pair("easy", decimal("0.4"), decimal("0.04")),
      pair("easy", decimal("2.8"), decimal("2.6")),
      pair("easy", decimal("0.9"), decimal("0.6")),
      pair("easy", decimal("1.0"), decimal("1.00")),
      pair("easy", decimal("0.2"), decimal("0.5")),
      pair("easy", decimal("3.4"), decimal("3.1")),
      pair("easy", decimal("0.8"), decimal("0.08")),
      pair("easy", decimal("2.2"), decimal("2.20")),
      pair("easy", decimal("0.1"), decimal("0.01")),
      pair("easy", decimal("4.5"), decimal("4.2")),
      pair("easy", decimal("0.6"), decimal("0.06")),
      pair("easy", decimal("1.1"), decimal("1.10")),
      pair("medium", decimal("0.45"), decimal("0.5")),
      pair("medium", decimal("0.09"), decimal("0.1")),
      pair("medium", decimal("1.05"), decimal("1.5")),
      pair("medium", decimal("0.80"), decimal("0.8")),
      pair("medium", decimal("3.14"), decimal("3.41")),
      pair("medium", decimal("0.36"), decimal("0.4")),
      pair("medium", decimal("2.05"), decimal("2.50")),
      pair("medium", decimal("0.70"), decimal("0.7")),
      pair("medium", decimal("4.08"), decimal("4.8")),
      pair("medium", decimal("0.19"), decimal("0.2")),
      pair("medium", decimal("0.55"), decimal("0.505")),
      pair("medium", decimal("3.02"), decimal("3.2")),
      pair("hard", decimal("0.099"), decimal("0.1")),
      pair("hard", decimal("2.030"), decimal("2.03")),
      pair("hard", decimal("0.505"), decimal("0.55")),
      pair("hard", decimal("1.009"), decimal("1.09")),
      pair("hard", decimal("0.875"), decimal("0.87")),
      pair("hard", decimal("0.101"), decimal("0.11")),
      pair("hard", decimal("3.004"), decimal("3.04")),
      pair("hard", decimal("0.660"), decimal("0.66")),
      pair("hard", decimal("4.099"), decimal("4.1")),
      pair("hard", decimal("0.808"), decimal("0.88")),
      pair("hard", decimal("5.010"), decimal("5.01")),
      pair("hard", decimal("0.333"), decimal("0.34"))
    ]
  },
  {
    page: 4,
    title: "Comparing Decimals",
    label: "Comparing decimals B",
    kind: "decimal",
    instruction:
      "Write <, > or = in each box. Extra zeros after the last non-zero digit do not change the value.",
    problems: [
      pair("easy", decimal("0.6"), decimal("0.60")),
      pair("easy", decimal("0.25"), decimal("0.52")),
      pair("easy", decimal("4.1"), decimal("4.01")),
      pair("easy", decimal("0.8"), decimal("0.08")),
      pair("easy", decimal("1.3"), decimal("1.30")),
      pair("easy", decimal("0.5"), decimal("0.05")),
      pair("easy", decimal("2.0"), decimal("2.00")),
      pair("easy", decimal("0.9"), decimal("0.90")),
      pair("easy", decimal("3.7"), decimal("3.07")),
      pair("easy", decimal("1.4"), decimal("1.04")),
      pair("easy", decimal("0.3"), decimal("0.30")),
      pair("easy", decimal("5.2"), decimal("5.02")),
      pair("easy", decimal("0.4"), decimal("0.40")),
      pair("easy", decimal("6.1"), decimal("6.01")),
      pair("easy", decimal("0.7"), decimal("0.07")),
      pair("medium", decimal("0.375"), decimal("0.38")),
      pair("medium", decimal("5.05"), decimal("5.005")),
      pair("medium", decimal("0.25"), decimal("0.250")),
      pair("medium", decimal("2.19"), decimal("2.9")),
      pair("medium", decimal("0.404"), decimal("0.44")),
      pair("medium", decimal("0.625"), decimal("0.65")),
      pair("medium", decimal("1.08"), decimal("1.8")),
      pair("medium", decimal("0.909"), decimal("0.99")),
      pair("medium", decimal("6.70"), decimal("6.7")),
      pair("medium", decimal("0.03"), decimal("0.003")),
      pair("medium", decimal("1.25"), decimal("1.025")),
      pair("medium", decimal("0.48"), decimal("0.5")),
      pair("hard", decimal("0.089"), decimal("0.09")),
      pair("hard", decimal("1.101"), decimal("1.11")),
      pair("hard", decimal("0.999"), decimal("1.0")),
      pair("hard", decimal("3.070"), decimal("3.07")),
      pair("hard", decimal("0.625"), decimal("0.62")),
      pair("hard", decimal("0.202"), decimal("0.22")),
      pair("hard", decimal("7.009"), decimal("7.09")),
      pair("hard", decimal("0.550"), decimal("0.55")),
      pair("hard", decimal("2.998"), decimal("3.00")),
      pair("hard", decimal("0.707"), decimal("0.77")),
      pair("hard", decimal("8.001"), decimal("8.01")),
      pair("hard", decimal("0.990"), decimal("0.99"))
    ]
  },
  {
    page: 5,
    title: "Comparing Fractions",
    label: "Comparing fractions A",
    kind: "fraction",
    instruction:
      "Write <, > or = in each box. Same denominators are straightforward; unlike fractions need a common denominator.",
    problems: [
      pair("easy", fraction(1, 4), fraction(3, 4)),
      pair("easy", fraction(2, 5), fraction(2, 5)),
      pair("easy", fraction(1, 3), fraction(2, 3)),
      pair("easy", fraction(3, 8), fraction(5, 8)),
      pair("easy", fraction(4, 6), fraction(1, 6)),
      pair("easy", fraction(1, 5), fraction(4, 5)),
      pair("easy", fraction(2, 7), fraction(2, 7)),
      pair("easy", fraction(3, 10), fraction(9, 10)),
      pair("easy", fraction(5, 9), fraction(2, 9)),
      pair("easy", fraction(7, 8), fraction(3, 8)),
      pair("easy", fraction(2, 6), fraction(5, 6)),
      pair("easy", fraction(8, 10), fraction(3, 10)),
      pair("medium", fraction(1, 2), fraction(2, 4)),
      pair("medium", fraction(2, 3), fraction(4, 6)),
      pair("medium", fraction(1, 2), fraction(3, 8)),
      pair("medium", fraction(3, 4), fraction(5, 8)),
      pair("medium", fraction(2, 5), fraction(1, 2)),
      pair("medium", fraction(3, 5), fraction(6, 10)),
      pair("medium", fraction(1, 4), fraction(2, 6)),
      pair("medium", fraction(5, 6), fraction(2, 3)),
      pair("medium", fraction(4, 8), fraction(1, 2)),
      pair("hard", fraction(3, 7), fraction(2, 5)),
      pair("hard", fraction(5, 6), fraction(7, 8)),
      pair("hard", fraction(4, 9), fraction(3, 7)),
      pair("hard", fraction(5, 12), fraction(2, 5)),
      pair("hard", fraction(7, 10), fraction(3, 4)),
      pair("hard", fraction(8, 15), fraction(5, 9))
    ]
  },
  {
    page: 6,
    title: "Comparing Fractions",
    label: "Comparing fractions B",
    kind: "fraction",
    instruction:
      "Write <, > or = in each box. Mixed numbers and improper fractions name the same amounts when they are equivalent.",
    problems: [
      pair("easy", fraction(1, 5), fraction(3, 5)),
      pair("easy", fraction(2, 8), fraction(1, 4)),
      pair("easy", fraction(3, 10), fraction(7, 10)),
      pair("easy", fraction(1, 6), fraction(5, 6)),
      pair("easy", fraction(4, 4), fraction(1, 1)),
      pair("easy", fraction(2, 9), fraction(7, 9)),
      pair("easy", fraction(3, 6), fraction(1, 2)),
      pair("easy", fraction(4, 8), fraction(3, 8)),
      pair("easy", fraction(5, 5), fraction(5, 5)),
      pair("easy", fraction(1, 10), fraction(9, 10)),
      pair("easy", fraction(2, 4), fraction(1, 2)),
      pair("easy", fraction(6, 9), fraction(2, 9)),
      pair("medium", fraction(3, 5), fraction(5, 8)),
      pair("medium", fraction(2, 3), fraction(5, 9)),
      pair("medium", fraction(7, 10), fraction(2, 3)),
      pair("medium", fraction(5, 6), fraction(4, 5)),
      pair("medium", fraction(1, 2, 1), fraction(3, 2)),
      pair("medium", fraction(4, 9), fraction(2, 5)),
      pair("medium", fraction(3, 4), fraction(7, 10)),
      pair("medium", fraction(1, 4, 2), fraction(9, 4)),
      pair("medium", fraction(5, 10), fraction(1, 2)),
      pair("hard", fraction(1, 3, 2), fraction(2, 5, 2)),
      pair("hard", fraction(5, 8), fraction(7, 12)),
      pair("hard", fraction(1, 4, 3), fraction(13, 4)),
      pair("hard", fraction(11, 6), fraction(2, 3, 1)),
      pair("hard", fraction(4, 15), fraction(3, 10)),
      pair("hard", fraction(1, 6, 5), fraction(31, 6))
    ]
  }
] as const satisfies readonly ComparingNumbersSheet[];
